//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pubs
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pubsEntities1 : DbContext
    {
        internal IEnumerable<object> employee;

        public pubsEntities1()
            : base("name=pubsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<pub_info> pub_info { get; set; }
        public DbSet<publisher> publishers { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<titleauthor> titleauthors { get; set; }
        public DbSet<title> titles { get; set; }
        public DbSet<discount> discounts { get; set; }
        public DbSet<roysched> royscheds { get; set; }
    }
}
