//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        public publisher()
        {
            this.employees = new HashSet<employee>();
            this.titles = new HashSet<title>();
        }
    
        public string pub_id { get; set; }
        public string pub_name { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual pub_info pub_info { get; set; }
        public virtual ICollection<title> titles { get; set; }
    }
}
