//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.sales = new HashSet<sale>();
            this.discounts = new HashSet<discount>();
        }
    
        public string stor_id { get; set; }
        public string stor_name { get; set; }
        public string stor_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
    
        public virtual ICollection<sale> sales { get; set; }
        public virtual ICollection<discount> discounts { get; set; }
    }
}
